# -*- coding: utf-8 -*-
"""movie_recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123bqjk8i8L9aFfFx6AETmcdavzd1WvHr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import drive

# Mount Drive
drive.mount('/content/drive')

"""**Setup & Data Loading**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import drive


# UPDATE THESE PATHS to match your Drive folder structure
movies_path = '/content/drive/MyDrive/MovieProject/movies.csv'
ratings_path = '/content/drive/MyDrive/MovieProject/ratings.csv'

movies = pd.read_csv(movies_path)
ratings = pd.read_csv(ratings_path)

print("Project Data Loaded Successfully!")

"""**Exploratory Data Analysis (EDA)**"""

# 1. Visualize Top 10 Genres
# We explode the genres but reset the index to avoid the 'duplicate labels' error
all_genres = movies['genres'].str.split('|').explode().reset_index(drop=True)

plt.figure(figsize=(10, 5))
# Fixed the FutureWarning by adding hue and legend=False
sns.countplot(
    y=all_genres,
    order=all_genres.value_counts().index[:10],
    hue=all_genres,
    palette='viridis',
    legend=False
)

plt.title('Top 10 Most Frequent Movie Genres')
plt.xlabel('Count')
plt.ylabel('Genre')
plt.show()

# 2. Rating Distribution (Standard Histogram)
plt.figure(figsize=(8, 4))
sns.histplot(ratings['rating'], bins=10, kde=True, color='royalblue')
plt.title('Distribution of User Ratings')
plt.xlabel('Rating (1-5)')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.3)
plt.show()

"""**Building the Recommendation Engine**"""

!pip install fuzzywuzzy python-Levenshtein

# =================================================================
# FINAL INTEGRATED PROJECT: DYNAMIC MOVIE RECOMMENDATION SYSTEM
# =================================================================
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
from fuzzywuzzy import process # For misspelled titles
from google.colab import drive

# 1. SETUP & DATA
drive.mount('/content/drive')
movies = pd.read_csv('/content/drive/MyDrive/MovieProject/movies.csv')
ratings = pd.read_csv('/content/drive/MyDrive/MovieProject/ratings.csv')

# Preprocessing
movies['genres_cleaned'] = movies['genres'].str.replace('|', ' ', regex=False)

# --- 2. ENGINE A: CONTENT-BASED (The 'Genre' Expert) ---
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movies['genres_cleaned'])
content_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

# --- 3. ENGINE B: COLLABORATIVE (The 'People' Expert) ---
# Filter to movies with at least 50 ratings for high-quality results
movie_counts = ratings.groupby('movieId').count()
popular_movies = movie_counts[movie_counts['rating'] >= 50].index
ratings_filtered = ratings[ratings['movieId'].isin(popular_movies)]

user_item_matrix = ratings_filtered.pivot(index='movieId', columns='userId', values='rating').fillna(0)
movie_sparse = csr_matrix(user_item_matrix.values)
model_knn = NearestNeighbors(metric='cosine', algorithm='brute')
model_knn.fit(movie_sparse)

# --- 4. THE INTERACTIVE TESTING FUNCTION ---
def run_recommendation_showdown():
    print("--- 🎬 MOVIE RECOMMENDATION SYSTEM SHOWDOWN ---")
    user_input = input("Enter a movie you liked (e.g., 'Toy Story' or 'Iron Man'): ")

    # Fuzzy Matching to find the exact title in our CSV
    all_titles = movies['title'].tolist()
    closest_match = process.extractOne(user_input, all_titles)
    movie_title = closest_match[0]
    print(f"\nSearching for: '{movie_title}' (Confidence: {closest_match[1]}%)")
    print("="*60)

    # --- EXECUTE CONTENT-BASED ---
    idx = movies.index[movies['title'] == movie_title][0]
    c_scores = list(enumerate(content_sim[idx]))
    c_scores = sorted(c_scores, key=lambda x: x[1], reverse=True)[1:6]
    content_list = [movies.iloc[i[0]]['title'] for i in c_scores]

    # --- EXECUTE COLLABORATIVE ---
    m_id = movies[movies['title'] == movie_title]['movieId'].values[0]
    try:
        m_idx = user_item_matrix.index.get_loc(m_id)
        distances, indices = model_knn.kneighbors(user_item_matrix.iloc[m_idx, :].values.reshape(1, -1), n_neighbors=6)
        collab_list = []
        for i in range(1, len(indices.flatten())):
            suggested_id = user_item_matrix.index[indices.flatten()[i]]
            collab_list.append(movies[movies['movieId'] == suggested_id]['title'].values[0])
    except KeyError:
        collab_list = ["Not enough rating data for this movie."]

    # --- DISPLAY RESULTS ---
    results_df = pd.DataFrame({
        "Content-Based (Similar Genres)": content_list,
        "Collaborative (Similar Users)": collab_list
    })
    print(results_df)

    # --- THE CRITICAL COMPARISON ---
    print("\n" + "="*60)
    print("🎓 WHICH IS BETTER?")
    print("1. CONTENT-BASED is better for 'Cold Start' (new movies) or niche genres.")
    print("2. COLLABORATIVE is better for 'Discovery'—it finds movies you'll like even if they are in different genres.")
    print("3. VERDICT: A HYBRID system is the industry standard (used by Netflix).")

# 5. RUN THE TEST
run_recommendation_showdown()